chore(setup-react-app): setting up React project
andela/caret-bn-frontend pull request #1
Opened 2019-11-25 14:32 UTC by ngireric123

#### What does this PR do?
Setting up React project for barefoot nomad frontend.

#### Description of Task to be completed?
- add .gitignore file
- Add .babelrc file
- Add islintignore file
- Add web pack.config file
- Add src folder
- install webpack 
- install babel
- eslint

#### How should this be manually tested?
- npm install
- npm start
- Then browser open itself
#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168781612](https://www.pivotaltracker.com/story/show/168781612)

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/38130305/69548568-40871500-0fa0-11ea-89d0-9c5279f132d8.png)

Questions:
N/A

2019-11-25 15:59 UTC, sabin18 approved these changes
@ngireric123  good job

2019-11-25 16:21 UTC, nignanthomas commented on src/index.js
> +ReactDOM.render(<App />, document.getElementById('app'));
Kindly add a new line at the end of the file.

2019-11-25 16:22 UTC, nignanthomas requested changes
Great job @ngireric123 
I left a comment. Kindly implement it.
And edit the PR's title to match conventions.

2019-11-25 17:17 UTC, nignanthomas approved these changes

2019-11-26 07:34 UTC, Cheza-Dzabala approved these changes
Good job

2019-11-26 09:30 UTC, alainmateso approved these changes

2019-11-26 09:33 UTC, merged