#168781623 User Login
andela/caret-bn-frontend pull request #14
Opened 2019-12-04 11:41 UTC by alainmateso

#### What does this PR do?
Adds user login functionality

#### Description of Task to be completed?
- adds user Login functionality
- adds tests for the functionality

#### How should this be manually tested?

- Clone ft-user-login-168781623 branch
- run `npm i`
- run `npm run dev`
- navigate to localhost:<:port>/users
- Fill the login form
- submit

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#168781623

#### Screenshots (if appropriate)
<img width="1422" alt="Screen Shot 2019-12-04 at 13 34 52" src="https://user-images.githubusercontent.com/50104386/70139622-85dfcc80-169b-11ea-8fab-3d0b21543a00.png">
<img width="1422" alt="Screen Shot 2019-12-04 at 13 35 11" src="https://user-images.githubusercontent.com/50104386/70139623-86786300-169b-11ea-968b-48fb1d66e81d.png">

#### Questions:
N/A

2019-12-05 09:34 UTC, nignanthomas requested changes
Nice job @alainmateso so far. However
What do you think about naming the button `LOGIN` instead? and some margin-top.
Also add a `padding-left` of about `0.5 rem` will look great, right?

Also a little bit of padding above between the `Header` text and `AuthHolder` would be great.

Last but not least `increase your test coverage`.

Regards

2019-12-08 19:56 UTC, sabin18 commented on src/actions/authActions.js
> +
remove this line.

2019-12-08 19:56 UTC, sabin18 commented on src/components/features/login/Login.js
> +
remove this line.

2019-12-08 20:01 UTC, sabin18 requested changes
Good job @alainmateso However, add route path on Login component in the AuthHolder component because we will add other components there.

2019-12-09 08:21 UTC, sabin18 approved these changes

2019-12-09 08:40 UTC, nignanthomas commented on src/components/features/login/Login.js
> +/* eslint-disable camelcase */
Kindly rename to `src/components/pages/Login.js`

2019-12-09 08:41 UTC, nignanthomas commented on src/components/features/login/Login.js
> +
Remove this line

2019-12-09 08:43 UTC, nignanthomas commented on src/components/features/login/Login.js
> +        <Input type="password" name="password" placeholder="Password..." onChange={this.handleChange} required />
Pass in the value attributes here because it is set as isRequired props in the Input component and complaining.

2019-12-09 08:51 UTC, nignanthomas requested changes
@alainmateso Great job bro
Tested and working as expected. Creating the token in localStorage

However left a few comments. kindly act on it ASAP.
I've also sent a few screenshots, check them out and act on it.
Kindly also test `App.js` `mapStateToProps` to increase coverage to `100%` sharp 😄 

Regards 👍

2019-12-09 19:48 UTC, merged