#168781621 - Signup Users
andela/caret-bn-frontend pull request #15
Opened 2019-12-04 11:53 UTC by nignanthomas

#### What does this PR do?
Signup Users

#### Description of Task to be completed?
- Create global components Button, ToastContainer
- Create signupActions and Reducers
- Create Register view

#### How should this be manually tested?
- Clone ft-signup-168781621 branch
- run `npm i`
- run `npm run dev`
- navigate to localhost:<:port>/users
- Fill the login form
- `Register`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168781621](https://www.pivotaltracker.com/story/show/168781621)

#### Screenshots (if appropriate)
<img width="1133" alt="Screen Shot 2019-12-04 at 13 29 53" src="https://user-images.githubusercontent.com/42959540/70140462-66e23a00-169d-11ea-90b2-e2fad024f3af.png">

#### Questions:
N/A

2019-12-04 20:23 UTC, alainmateso requested changes
Great job Thomas, Kindly return a descriptive message when a user enters data that don't match the required pattern.

2019-12-05 08:05 UTC, ngireric123 commented
Great job @nignanthomas kindly try to increase test coverage

2019-12-05 08:40 UTC, ngireric123 requested changes
@nignanthomas kindly  increase test coverage

2019-12-05 12:15 UTC, nakiwuge commented on src/actions/SignupAction.js
> +const appUrl = 'https://caret-bn-backend-staging.herokuapp.com/api/v1';
Configure axios with  the baseUrl

2019-12-05 12:33 UTC, nakiwuge commented on src/actions/SignupAction.js
> +// export default { signupAction, resetSignup };
Make this file to have all auth Actions. Create one type function to be used in all the auth action functions. something like this
```
const authType = (type,payload)=>{
type,
payload
}

Make signUp action cleaner with something like this
```
  axios.post(`${appUrl}/users/register`, userData)
    .then((response) => {
        dispatch(authType(SIGNUP_SUCCESS,response))
    })
    .catch((error) => {
 dispatch(authType(SIGNUP_FAIL,error.reponse))
    });
};

2019-12-05 12:34 UTC, nakiwuge commented on src/actions/SignupAction.js
> +      dispatch({
Kindly create an `isLoading` state in the component where you call this action to cater for loading

2019-12-05 12:35 UTC, nakiwuge commented on src/actions/SignupAction.js
> +// module.exports = { signupAction, resetSignup };
Remove commented code

2019-12-05 12:41 UTC, nakiwuge commented on src/components/features/Signup.js
> +    const handleChange = (e) => {
Move this method out of the render

2019-12-05 12:53 UTC, nakiwuge commented on src/reducers/signupReducer.js
> +  signupSuccess: false,
rename `signupSuccess` to `data: null`

2019-12-05 12:55 UTC, nakiwuge commented on src/reducers/signupReducer.js
> +// export default signupReducer;
remove commented code

2019-12-05 12:58 UTC, nakiwuge commented on src/styles/styles.scss
> +    > div{
remove `>`

2019-12-05 13:00 UTC, nakiwuge commented on src/styles/styles.scss
> +			width: 150px;
Indent button

2019-12-05 13:02 UTC, nakiwuge commented on src/styles/styles.scss
> +    > form Input{
use sass here like this 
``` form{
Input{
        width: 80%;
        padding-left: 0.5rem;
    }
} 
```

2019-12-05 13:03 UTC, nakiwuge commented on src/tests/SignupTest.spec.js
> +
remove this line

2019-12-05 13:04 UTC, nakiwuge commented on src/tests/SignupTest.spec.js
> +  //   expect(wrapper.find('').text()).toBe('');
remove this commented code

2019-12-05 13:04 UTC, nakiwuge commented on src/tests/actionsTests/SignupActionsTest.spec.js
> +// import store from '../../reduxStore';
remove this commented code

2019-12-05 13:04 UTC, nakiwuge commented on src/tests/actionsTests/SignupActionsTest.spec.js
> +
remove this line

2019-12-08 12:37 UTC, ngireric123 approved these changes
LGTM

2019-12-09 06:48 UTC, alainmateso approved these changes

2019-12-09 08:34 UTC, merged