ft(Handle-User-Verification ): Handle User Verification for caret-bac…
andela/caret-bn-frontend pull request #16
Opened 2019-12-05 07:16 UTC by ngireric123

…kend

- Created UserVerify functional component
- Installed react-toastify

[Finishes #169889384]

#### What does this PR do?
* Handle User Verification
#### Description of Task to be completed?
* create component userVerify
#### How should this be manually tested?
* Clone ft-user-verification-169889384
* run npm i
* run npm run dev
* navigate to postman
* Register a new user
* after making registration go in your email
* click on verify button

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#169889384
#### Screenshots (if appropriate)

#### Questions:

2019-12-06 07:53 UTC, nignanthomas requested changes
Well done @ngireric123 
However, as per Miriam requirements, put the backend base Url in a helper named for example `backendCall.js` as we did.

And kindly implement a spinner/loader when to display while the request is pending.

Thanks

2019-12-09 07:05 UTC, Cheza-Dzabala commented on src/index.html
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css" integrity="sha384-i1LQnF23gykqWXg6jxC2ZbCbUMxyw5gLZY6UiUS98LYV5unm8GWmfkIS6jqJfb4E" crossorigin="anonymous">
Swap this with [this](https://github.com/FortAwesome/react-fontawesome) font-awesome react package.

2019-12-09 07:12 UTC, Cheza-Dzabala reviewed
Good job but please see comments made

2019-12-09 07:12 UTC, Cheza-Dzabala commented on src/index.html
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css" integrity="sha384-i1LQnF23gykqWXg6jxC2ZbCbUMxyw5gLZY6UiUS98LYV5unm8GWmfkIS6jqJfb4E" crossorigin="anonymous">
Swap this with [this](https://github.com/FortAwesome/react-fontawesome) font-awesome react package.

2019-12-09 07:12 UTC, Cheza-Dzabala commented on src/helpers/backendCall.js
> +  baseURL: 'https://caret-bn-backend-staging.herokuapp.com/api/v1',
Export this url to a utility file and import it. That file will hold the endpoints and make it possible to change endpoints based on the environment.

2019-12-09 07:12 UTC, Cheza-Dzabala commented on src/actions/verifyUserAction.js
> +export const VerifyUsers = (token) => (dispatch) => {
Put a new line here.

2019-12-09 07:12 UTC, Cheza-Dzabala commented on src/actions/verifyUserAction.js
> +import {
Put a new line here

2019-12-09 15:05 UTC, Cheza-Dzabala approved these changes

2019-12-09 15:07 UTC, nignanthomas requested changes
Great job @ngireric123 . However:

- Put your `userVerifyActions` in `authActions.js`.
- Remove `pending` from `reducers`, `actions` and `wherever you are testing it`.

2019-12-09 15:21 UTC, nignanthomas approved these changes

2019-12-10 11:54 UTC, merged