FT Social Media Login
andela/caret-bn-frontend pull request #17
Opened 2019-12-05 10:06 UTC by Cheza-Dzabala

#### What does this PR do?

Allows a user to authenticate their account using Facebook & Google

#### Description of Task to be completed?
- A user should be able to login by Facebook
- A user should be able to login by Google

#### How should this be manually tested?
- Clone this Repo
- Run npm install
- Run npm run dev
- Access localhost:8080/users/login
- Select Either Facebook or Google
- Note authentication

#### Any background context you want to provide?
N / A
#### What are the relevant pivotal tracker stories?
###### #168781624
#### Screenshots (if appropriate)
<img width="752" alt="Screen Shot 2019-12-03 at 15 26 16" src="https://user-images.githubusercontent.com/13886438/70225368-935a8c80-1757-11ea-8c62-48ff7bfe26c3.png">
<img width="674" alt="Screen Shot 2019-12-05 at 12 04 54" src="https://user-images.githubusercontent.com/13886438/70225369-935a8c80-1757-11ea-98c1-9a5f03aa5d97.png">
<img width="553" alt="Screen Shot 2019-12-05 at 12 05 03" src="https://user-images.githubusercontent.com/13886438/70225370-93f32300-1757-11ea-8376-eebff762b7ca.png">
<img width="482" alt="Screen Shot 2019-12-05 at 12 05 25" src="https://user-images.githubusercontent.com/13886438/70225372-93f32300-1757-11ea-9bab-06058718833c.png">

#### Questions:
N / A

2019-12-09 07:25 UTC, alainmateso requested changes
Great Job Cheza. Kindly revise your Google Login. It seems like the backend app breaks when you try to login with google.

2019-12-09 10:53 UTC, sabin18 approved these changes
@Cheza-Dzabala  good job!

2019-12-09 11:58 UTC, nakiwuge commented on src/actions/authActions.js
> +};
Give this function a more meaningful name. Also remove the pending type and move it to the component by creating an `isLoading` state

2019-12-09 11:58 UTC, nakiwuge commented on src/actions/authActions.js
> +  window.localStorage.setItem('token', userData.token);
you can use localStorage.setItem()

2019-12-09 12:00 UTC, nakiwuge commented on src/components/Register.js
> +}
remove this file

2019-12-09 12:13 UTC, nakiwuge commented on src/components/pages/SocialButtons.js
> +
reuse the button component

2019-12-09 12:17 UTC, nakiwuge commented on src/tests/actionsTests/SocialAuthActionTest.spec.js
> +describe('Redux', () => {
Give a describe a more descriptive test

2019-12-09 12:27 UTC, nakiwuge commented on src/views/AuthSuccess.js
> +const AuthSuccess = (props) => {
Rename this function to `SocialAuth`

2019-12-09 12:27 UTC, nakiwuge commented on src/views/AuthSuccess.js
> +  saveUserToState(user);
Put this in componentDidMount()

2019-12-10 09:01 UTC, alainmateso approved these changes

2019-12-10 09:02 UTC, merged