#168781627 - Users can view all requests and a single request
andela/caret-bn-frontend pull request #23
Opened 2019-12-11 13:22 UTC by nignanthomas

#### What does this PR do?
Users can view all requests and a single request

#### Description of Task to be completed?
- Create menuBar component
- Create ViewRequests component
- Create requestItem component
- Create ViewSingleRequest component
- Create tests

#### How should this be manually tested?
- Clone ft-view-requests-168781627 branch
- run `npm i`
- run `npm run dev`
- Click on `Requests` in the MenuBar

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168781627](https://www.pivotaltracker.com/story/show/168781627)

#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2019-12-11 at 15 18 06" src="https://user-images.githubusercontent.com/42959540/70624937-0b2e2880-1c2a-11ea-9ef9-6c3251522458.png">

#### Questions:
N/A

2019-12-12 09:09 UTC, ngireric123 approved these changes
LGTM

2019-12-12 09:09 UTC, sabin18 commented on src/tests/mocks/requestsMocks.js
> +
remove this line

2019-12-12 09:10 UTC, sabin18 commented on src/tests/requestsTests/SingleRequestTest.spec.js
> +  // it('Should Simulate Successfull Signup', () => {
remove comments here.

2019-12-12 09:11 UTC, sabin18 commented on src/tests/requestsTests/ViewRequests.spec.js
> +  // it('Should Simulate Successfull Signup', () => {
remove commented lines here.

2019-12-12 09:12 UTC, sabin18 commented on src/styles/styles.scss
> +	// border-radius: 0 !important;
remove this commented line.

2019-12-12 09:13 UTC, sabin18 commented on src/styles/requests/index.scss
> +// .row-end {
remove these commented lines.

2019-12-12 09:19 UTC, sabin18 requested changes
Good job @nignanthomas, work on comments I left.

2019-12-12 09:29 UTC, sabin18 approved these changes

2019-12-12 11:16 UTC, nakiwuge commented on src/styles/menuBar.scss
> +		display: flex;
Indent this

2019-12-12 11:16 UTC, nakiwuge commented on src/styles/menuBar.scss
> +		width: 35px;
Indent this

2019-12-12 11:16 UTC, nakiwuge commented on src/styles/requests/destinations.scss
> +		display: flex;
Indent this

2019-12-12 11:16 UTC, nakiwuge commented on src/styles/requests/index.scss
> +		display: flex;
Indent this

2019-12-12 11:19 UTC, nakiwuge commented on src/views/requests/SingleRequest.js
> +
remove this line

2019-12-12 11:19 UTC, nakiwuge commented on src/views/requests/ViewRequests.js
> +
remove this line

2019-12-12 11:35 UTC, nakiwuge requested changes
@nignanthomas good job on the implementation however you need to create a `protectedRoute` component for the routes you don't want a user to access without logging in. You also need to check if the token provided is valid or not expired. If the token is invalid/expired redirect the user to the login page.
Also, it is bad practice to import the navbar in every component. 
Checkout these links to get started
- https://medium.com/@leonardobrunolima/react-tips-how-to-protect-routes-for-unauthorized-access-with-react-router-v4-73c0d451e0a2
- https://dev.to/calier/setting-up-an-authenticated-route-in-react-4m9a
- https://www.youtube.com/watch?v=Y0-qdp-XBJg

2019-12-13 07:31 UTC, nakiwuge approved these changes

2019-12-13 07:32 UTC, merged