#168781646: Add accommodation
andela/caret-bn-frontend pull request #26
Opened 2019-12-12 20:05 UTC by alainmateso

#### What does this PR do?
Create new  accommodation facilities

#### Description of Task to be completed?
suppliers and travel admins can create accommodations

#### How should this be manually tested?
Clone this branch
run `npm i`
run `npm run dev`
navigate to `http://localhost:<:port>/accommodations/new`
fill the form with valid data
Click create

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#168781646

#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2019-12-12 at 22 03 54" src="https://user-images.githubusercontent.com/50104386/70744874-52e8a900-1d2b-11ea-9ce3-542e19740588.png">

#### Questions:
N/A

2019-12-12 20:23 UTC, sabin18 requested changes
good job @alainmateso, work on the comment.

2019-12-12 20:23 UTC, sabin18 commented on src/components/Home.js
> +// import { Container } from 'react-bootstrap';
remove this comment

2019-12-13 09:38 UTC, sabin18 approved these changes

2019-12-13 09:41 UTC, ngireric123 approved these changes
LGTM

2019-12-13 09:59 UTC, nakiwuge commented on src/actions/accommodationActions.js
> +const operationType = (type, payload) => ({
rename this to `accommodationType`

2019-12-13 10:00 UTC, nakiwuge commented on src/actions/locationActions.js
> +const authType = (type, payload) => ({
rename this to `locationsType`

2019-12-13 10:02 UTC, nakiwuge commented on src/components/pages/CreateAccommodation.js
> +          window.location.replace(`/accommodations/${accommodationData.data.slug}`);
Make use of react by using  `history.push`

2019-12-13 10:06 UTC, nakiwuge commented on src/views/accommodations/NewAccommodation.js
> +
remove this line

2019-12-13 10:06 UTC, nakiwuge commented on src/views/accommodations/AllAccommodations.js
> +
remove this line

2019-12-13 14:05 UTC, merged