feature(update profile ): update user profile picture
andela/caret-bn-frontend pull request #27
Opened 2019-12-13 08:51 UTC by ngireric123

- Add action
- Add component for userProfile
Users should be able to view and edit their profiles
[Finishes #168781625]

#### What does this PR do?
Update profile
#### Description of Task to be completed?
Users should be able to view and edit their profiles
#### How should this be manually tested?
Clone ft-view-edit-profile-168781625 branch
run `npm i`
run `npm run dev`
navigate to `http://localhost:<:port>/profile`
edit the form with valid data
click on send
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#168781625
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/38130305/70787035-8f9dba00-1d96-11ea-910c-fa00620b8b91.png)

#### Questions:
N/A

2019-12-18 09:51 UTC, sabin18 commented on src/actions/profileAction.js
> +// import { checkEmail } from '../helpers/authHelper';
remove these comments.

2019-12-18 09:53 UTC, sabin18 commented on src/tests/actionsTests/profileActionsTest.spec.js
> +
remove these lines

2019-12-18 12:11 UTC, sabin18 requested changes
Good job @ngireric123 However increase your test coverage.

2019-12-18 15:12 UTC, alainmateso approved these changes

2019-12-18 15:57 UTC, sabin18 approved these changes

2019-12-19 09:15 UTC, nakiwuge commented on src/actions/profileAction.js
> +    window.location.replace('/profile');
Do not not usewindow.location.replace to redirect users because this loads the page. Use `Redirect` or `history.push` in the component

2019-12-19 09:17 UTC, nakiwuge commented on src/components/global/MenuComponent.js
> +
Remove this line

2019-12-19 09:18 UTC, nakiwuge commented on src/components/global/MenuComponentOld.js
> +export default MenuComponent;
Remove this file it is duplicate of another file

2019-12-19 09:22 UTC, nakiwuge commented on src/components/pages/profiles/UserProfile.js
> +      username: data.profile.username,
Destructure  the fields from from `data.profile`

2019-12-19 09:23 UTC, nakiwuge commented on src/components/pages/profiles/UserProfile.js
> +
remove this file

2019-12-19 09:27 UTC, nakiwuge commented on src/components/pages/profiles/UserProfile.js
> +      form.append('image', selectedFile);
These are if statements are too many there is a better way of validating the fields reach out to @alainmateso he worked on something similar

2019-12-19 09:27 UTC, nakiwuge commented on src/components/pages/profiles/UserProfile.js
> +    console.log('initial state', data);
remove  the console

2019-12-19 09:29 UTC, nakiwuge commented on src/tests/PageLoadingTest.spec.js
> +
remove this line

2019-12-19 09:32 UTC, nakiwuge commented on src/tests/PageLoadingTest.spec.js
> +    });
Remove this empty `it` block

2019-12-19 09:32 UTC, nakiwuge commented on src/tests/menuComponentOldTest.spec.js
> +
remove this line

2019-12-19 09:32 UTC, nakiwuge commented on src/tests/userProfilePageTest.spec.js
> +
remove this line

2019-12-19 09:33 UTC, nakiwuge commented on src/tests/userProfilePageTest.spec.js
> +      console.log(component.html());
remove console.log

2019-12-19 09:34 UTC, nakiwuge commented on src/tests/userProfilePageTest.spec.js
> +      component.instance().handleChange(event);
Give this it statement `description`  and an `expect`

2019-12-19 09:35 UTC, nakiwuge commented on src/tests/userProfilePageTest.spec.js
> +      component.instance().handleImage(eventFile);
Give this it statement description and an expect

2019-12-19 09:35 UTC, nakiwuge commented on src/tests/userProfilePageTest.spec.js
> +      instance.handleSubmit(fakeEvent);
Give this it statement description and an expect

2019-12-19 09:35 UTC, nakiwuge commented on src/tests/userProfilePageTest.spec.js
> +      global.document.body.appendChild(modalsContainer);
Give this it statement description and an expect

2019-12-19 09:35 UTC, nakiwuge commented on src/tests/userProfilePageTest.spec.js
> +
remove this line

2019-12-19 09:36 UTC, nakiwuge commented on src/tests/reducersTests/profileReducerTest.spec.js
> +
remove this line

2019-12-19 09:36 UTC, nakiwuge commented on src/tests/menuComponentOldTest.spec.js
> +    it('', () => {
remove this

2019-12-19 09:37 UTC, nakiwuge commented on src/tests/menuComponentOldTest.spec.js
> +  describe('hhhhhhhhhh', () => {
Give the describe a better description

2019-12-19 09:37 UTC, nakiwuge commented on src/tests/reducersTests/profileReducerTest.spec.js
> +
remove this line

2019-12-19 10:29 UTC, nakiwuge requested changes
@ngireric123 good job sofar. Kindly go through the comments I have left on this pr. Also work on the feedback below.
- Add a link to the user profile on the navbar.  The avatar should have a dropdown with a link to the profile page.
- When the user is on the profile page the fields should be grayed out (the user should not be able to type in the form fields) the same way you grayed out the email field.
- Add a link with `edit profile` so that the form fields become editable when it is clicked .This means the update button should only appear when the user has clicked `edit profile` .
- Add a loader to the update button and on successful update, the user should receive success message
- Your coverage should be 90+

2019-12-23 11:13 UTC, nakiwuge approved these changes

2019-12-23 11:16 UTC, merged