#170124090 -View All Accommodations and a Single Accommodation
andela/caret-bn-frontend pull request #28
Opened 2019-12-13 10:09 UTC by sabin18

#### What does this PR do?
PR to create View All Accommodations and a Single Accommodation pages
#### Description of Task to be completed?`
- add all accommodation page
- add specific accommodation page
- add AllAccommodation component
- add singleAccommodation component
#### How should this be manually tested?
Clone ft-view-all-accommodation-170124090
run npm i
run npm run dev
Click on Accommodations in the MenuBar
#### Any background context you want to provide?
`N/A`
#### What are the relevant pivotal tracker stories?
[#170124090](https://www.pivotaltracker.com/story/show/170124090)
#### Screenshots (if appropriate)
<img width="1434" alt="Screen Shot 2019-12-13 at 12 01 55" src="https://user-images.githubusercontent.com/47029978/70791961-de505180-1da0-11ea-894f-228472af70f1.png">
<img width="1434" alt="Screen Shot 2019-12-13 at 12 06 50" src="https://user-images.githubusercontent.com/47029978/70792082-23748380-1da1-11ea-9b2f-14c0ae6a16e5.png">

#### Questions:
`N/A`

2019-12-15 14:12 UTC, alainmateso requested changes
Amazing work Sabin! Kindly put a small space between an accommodation description and the booking container. They are too squeezed when viewing a single accommodation.

2019-12-16 11:06 UTC, alainmateso approved these changes

2019-12-16 13:03 UTC, nakiwuge commented on src/components/pages/SingleAccommodation.js
> +  singleAccommodation() {
rename this to renderAcommodation

2019-12-16 13:04 UTC, nakiwuge commented on src/tests/singleAccommodationTest.spec.js
> +
remove this

2019-12-16 14:21 UTC, merged