#168781631: assign user roles
andela/caret-bn-frontend pull request #32
Opened 2019-12-18 09:01 UTC by alainmateso

#### What does this PR do?
Assign user roles
#### Description of Task to be completed?
- Admin can view all users
- Admin can view a specific user
- Admin can assign a specific user a role

#### How should this be manually tested?

- Clone this branch
- run npm i
- run npm run dev
- in your browser navigate to localhost:<:port>/admin/users
- select any user of your choice
- select a new role
- press assign new role button

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#168781631
#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2019-12-18 at 10 49 14" src="https://user-images.githubusercontent.com/50104386/71071526-7aa19c00-2185-11ea-8616-3dce19917d63.png">
<img width="1440" alt="Screen Shot 2019-12-18 at 10 47 26" src="https://user-images.githubusercontent.com/50104386/71071545-82f9d700-2185-11ea-998c-89f57733c4bd.png">
<img width="1440" alt="Screen Shot 2019-12-18 at 10 51 49" src="https://user-images.githubusercontent.com/50104386/71071578-8f7e2f80-2185-11ea-9777-d7ad1836a158.png">
<img width="1440" alt="Screen Shot 2019-12-18 at 10 51 20" src="https://user-images.githubusercontent.com/50104386/71071587-9442e380-2185-11ea-9740-3e6e9cb2aea2.png">

#### Questions:
N/A

2019-12-18 11:31 UTC, Cheza-Dzabala reviewed
@alainmateso, great job! However, for the view that displays users to the admin, is it possible to use a data-table instead of the current way of displaying. You would have less code that does more. Maybe something like [this](https://www.npmjs.com/package/react-data-table-component).

2019-12-18 11:55 UTC, sabin18 commented on src/components/pages/admin/ViewSpecificUser.js
> +    // window.location.reload();
remove this line.

2019-12-18 14:14 UTC, nakiwuge commented on src/App.js
> +          <ProtectedRoute exact path="/admin/users/:userId" component={SpecificUSer} />
Use `username` instead of `userId` param

2019-12-18 14:15 UTC, nakiwuge commented on src/actions/userActions.js
> +export const getRoles = () => async (dispatch) => {
Move the roles actions to `roleAction` file

2019-12-18 14:21 UTC, nakiwuge commented on src/components/pages/admin/ViewSpecificUser.js
> +    const { assignRole: assignNewRole, userId, getSpecificUser: getOneUser } = this.props;
Move the constants above line 39

2019-12-18 14:23 UTC, nakiwuge commented on src/helpers/authHelper.js
> +    if (role !== 1) {
Add a new line

2019-12-18 14:23 UTC, nakiwuge commented on src/reducers/userReducer.js
> +    case FETCH_ROLES:
Move the roles to a rolesReducer

2019-12-18 14:25 UTC, nakiwuge commented on src/views/admin/ViewAllUsers.js
> +
remove this line

2019-12-18 14:25 UTC, nakiwuge commented on src/views/admin/ViewAllUsers.js
> +
remove this line

2019-12-18 14:31 UTC, nakiwuge requested changes
Good job @alainmateso , however I would like you to work on the feedback below.
- Remove the user ids from the cards where you are displaying users on `admin/users`
- Make the username on the card a heading so that it is bold
- Validate the `select role field` so that the user gets a descriptive error when he/she clicks `Assign role` without selecting a role. Currently, the error comes from the backend but it is too long
- Your coverage should be 90% plus
- check out for other comments  I have left on the pr

2019-12-19 14:38 UTC, Cheza-Dzabala approved these changes
Great job

2019-12-19 15:23 UTC, nakiwuge approved these changes

2019-12-19 15:24 UTC, merged