#168781629 - Users Filter Requests
andela/caret-bn-frontend pull request #33
Opened 2019-12-18 12:08 UTC by nignanthomas

#### What does this PR do?
Users Filter Requests.

#### Description of Task to be completed?
- Create searchBar Component with fields
- Create actions to fetch filtered requests

#### How should this be manually tested?
- Clone ft-filter-requests-168781629 branch
- run `npm i`
- run `npm run dev`
- Click on `Requests` in the MenuBar
- Click on `Filter Requests` to show/hide the Search Bar

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168781629](https://www.pivotaltracker.com/story/show/168781629)

#### Screenshots (if appropriate)
<img width="1438" alt="Screen Shot 2019-12-18 at 14 07 02" src="https://user-images.githubusercontent.com/42959540/71085302-d842e200-219f-11ea-9588-e856fffe35eb.png">
<img width="1401" alt="Screen Shot 2019-12-18 at 14 07 13" src="https://user-images.githubusercontent.com/42959540/71085304-d842e200-219f-11ea-8623-939437f9bf7b.png">
<img width="1440" alt="Screen Shot 2019-12-18 at 14 07 42" src="https://user-images.githubusercontent.com/42959540/71085306-d8db7880-219f-11ea-927e-1c18555ca7fa.png">

#### Questions:
N/A

2019-12-18 12:55 UTC, Cheza-Dzabala reviewed
@nignanthomas, looks good.. However, a user should not be able to enter a request id from the front end

2019-12-18 14:22 UTC, alainmateso commented on src/components/pages/requests/SearchComponent.js
> +
remove commented code

2019-12-18 14:23 UTC, alainmateso commented on src/components/pages/requests/SearchComponent.js
> +    console.log('searchParams ===> ', searchParams);
remove console.log statements

2019-12-18 14:23 UTC, alainmateso commented on src/components/pages/requests/SearchComponent.js
> +                {/* <DayPickerInput /> */}
remove commented code

2019-12-18 14:24 UTC, alainmateso commented on src/views/requests/ViewRequests.js
> +    console.log('searchDataError ===> ', searchDataError);
remove console.log statements

2019-12-18 14:24 UTC, alainmateso commented on src/views/requests/ViewRequests.js
> +    console.log('searchRequests ===> ', searchRequests);
remove console.log statements

2019-12-18 14:25 UTC, alainmateso commented on src/views/requests/ViewRequests.js
> +    // }
remove commented code

2019-12-18 14:25 UTC, alainmateso commented on src/views/requests/ViewRequests.js
>            {dataError && <Alert variant="danger" heading="Error" message={dataError.message} />}
remove commented code

2019-12-18 14:25 UTC, alainmateso commented on src/views/requests/ViewRequests.js
> +
remove commented code

2019-12-18 14:34 UTC, alainmateso requested changes
Great job @nignanthomas . Kindly work on the following feedback
- Since the id of the request is not displayed anywhere on the request information, kindly add it so that the search by id makes sense. 
- When no results are found, I believe it is better to use any other selector like just a label to tell the user that no requests were found instead of bring the alert component

I've also left a few comments, please check them out. Impressive work 👍🏾

2019-12-19 10:24 UTC, alainmateso approved these changes

2019-12-19 11:52 UTC, nakiwuge commented on src/components/pages/requests/SearchBar.js
> +    const { isLoading, openSearch, ...options } = state;
Add a new line

2019-12-19 11:52 UTC, nakiwuge commented on src/components/pages/requests/SearchBar.js
> +    searchParams = searchParams.substring(0, searchParams.length - 1);
Add a new line

2019-12-19 11:53 UTC, nakiwuge commented on src/components/pages/requests/SearchBar.js
> +    });
Add a new line

2019-12-19 11:53 UTC, nakiwuge commented on src/components/pages/requests/SearchBar.js
> +    }
Add a new line

2019-12-19 11:53 UTC, nakiwuge commented on src/components/pages/requests/SearchBar.js
> +    const { locations } = props;
Add a new line

2019-12-19 11:53 UTC, nakiwuge commented on src/components/pages/requests/SearchBar.js
> +            {/* <Col xs={12} sm={6} md={4} lg={4}>
Remove commented code

2019-12-19 11:54 UTC, nakiwuge commented on src/styles/requests/requests.scss
> +  background-color: #ffffff;
move this color to the variables

2019-12-19 11:54 UTC, nakiwuge commented on src/styles/breadcrumbs.scss
> +	background-color: #ffffff !important;
move this color to the variables

2019-12-19 12:00 UTC, nakiwuge requested changes
@nignanthomas this is great work however you have a date picker as one of the options but it doesn't have a label so a user cannot know whether its a date for creating a request or arrival date or destination date.

I have left other comments on the pr kindly check them out

2019-12-20 04:24 UTC, Cheza-Dzabala approved these changes

2019-12-20 05:26 UTC, nakiwuge approved these changes

2019-12-20 05:28 UTC, merged