168781651 -Users should be able to book an accommodation facility
andela/caret-bn-frontend pull request #34
Opened 2019-12-18 20:40 UTC by sabin18

#### What does this PR do?

#### Description of Task to be completed?
- PR to allow a user to book an accommodation
#### How should this be manually tested?
- add booking actions
- add booking reducer
- add booking functionalities
#### Any background context you want to provide?
`N/A`
#### What are the relevant pivotal tracker stories?
[#168781651 ](https://www.pivotaltracker.com/story/show/168781651)
#### Screenshots (if appropriate)
<img width="1421" alt="Screen Shot 2019-12-18 at 22 30 49" src="https://user-images.githubusercontent.com/47029978/71121464-30510700-21e7-11ea-89f4-7c5948a8c0f8.png">
<img width="1421" alt="Screen Shot 2019-12-18 at 22 32 29" src="https://user-images.githubusercontent.com/47029978/71121465-30e99d80-21e7-11ea-96ff-3445a0af3cd2.png">

#### Questions:
`N/A`

2019-12-20 13:32 UTC, nignanthomas commented on src/components/pages/SingleAccommodation.js
> +    await this.setState((state) => ({ ...state, checkOutDate: checkOutValue }));
If feasible, kindly refactor this functions.

2019-12-20 13:32 UTC, nignanthomas commented on src/components/pages/AllAccommodation.js
> +            create new accommodation
Capital `C`, please.

2019-12-20 13:33 UTC, nignanthomas commented on src/components/pages/SingleAccommodation.js
>            <Breadcrumbs itemsArray={['> Home', '  accommodations', post.name]} />
Capital `A`...

2019-12-20 13:37 UTC, nignanthomas requested changes
@sabin18 
Good job here bro

However, kindly note I have left comments and request for changes...
Also we have a `Make Booking` button in `All Accommodations` that does nothing. Kindly find it a functionnality. For example you can attach an hide/show modal that displays the booking component.

Thanks

2019-12-23 12:28 UTC, nakiwuge commented on src/components/pages/SingleAccommodation.js
> +  console.log('props', bookedError);
Remove console.log

2019-12-23 12:30 UTC, nakiwuge commented on src/components/pages/SingleAccommodation.js
> +  const { ownerUser } = post;
Equate this constant to accommodation directly to and remove line 90

2019-12-23 12:33 UTC, nakiwuge commented on src/components/pages/SingleAccommodation.js
> +renderAcommodation() {
This method is too long kindly create a separate component for bookings and call it in this component

2019-12-23 12:35 UTC, nakiwuge commented on src/styles/styles.scss
> +	background-color: rgb(233, 235, 238);
Put this color in variable s

2019-12-23 12:35 UTC, nakiwuge commented on src/tests/actionsTests/bookingActions.spec.js
> +
Remove this line

2019-12-23 12:47 UTC, nakiwuge reviewed
@sabin18 good job sofar. Kindly work on this feedback
- The `ViewSIngleAccommodation` component is too connected each you are supposed to create different components for rating and booking and then call them in this file. Since you are working on booking s create a separate component for bookings.
- When I try to book with invalid dates I get an error which is ok but when I provide valid data the error component still persists so both the previous error and success message are displayed.
- The `Number of rooms` place holder is cut off  in mobile view

2019-12-23 12:48 UTC, nakiwuge requested changes
@sabin18 good job sofar. Kindly work on this feedback
- The `ViewSIngleAccommodation` component is too connected each you are supposed to create different components for rating and booking and then call them in this file. Since you are working on booking s create a separate component for bookings.
- When I try to book with invalid dates I get an error which is ok but when I provide valid data the error component still persists so both the previous error and success message are displayed.
- The `Number of rooms` place holder is cut off  in mobile view

2019-12-27 09:49 UTC, ngireric123 approved these changes
LGTM

2019-12-27 09:49 UTC, ngireric123 commented on src/styles/pages/singleAccommodation.scss
>  }
add new line

2019-12-27 09:49 UTC, ngireric123 commented on src/tests/singleAccommodationPageTest.spec.js
> +
remove this line

2019-12-27 10:00 UTC, nignanthomas approved these changes

2019-12-27 10:32 UTC, nakiwuge approved these changes

2019-12-27 10:32 UTC, merged