#168781628 - Implementation of notifications Panel
andela/caret-bn-frontend pull request #41
Opened 2019-12-27 15:56 UTC by nignanthomas

#### What does this PR do?
Implementation of notifications Panel.

#### Description of Task to be completed?
- Create actions/reducers to get all notifications, mark them and switch notifications
- Create component to display all notifications and button to mark as read/unread
- Create dropdown to display 10 most recent notifications, mark all as read, see more

#### How should this be manually tested?
- Clone ft-notifications-pane-168781628 branch
- run `npm i`
- run `npm run dev`
- Click on `Notifications` dropdown to view most recent notifications and/or view all notifications
#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168781628](https://www.pivotaltracker.com/story/show/168781628)

#### Screenshots (if appropriate)

#### Questions:
N/A

2019-12-29 12:20 UTC, alainmateso requested changes
Great Job Thomas. Kindly work on the following feedback:

- When the user has no notifications, it is better to tell them in the panel instead of bringing mark all as read and see more because if a user clicks on see more, it only comes an empty page

- I believe the notification counter(the number itself) should be white to facilitate readability

- When I click on a request from a notification, it should mark that notification as read. It does not make sense to me to click on a notification and I doesn't turn to read. That means the user will always have unread notifications even though in reality they are read.

2019-12-29 12:24 UTC, ngireric123 reviewed
Great Job @nignanthomas  Kindly try to increase test coverage

2019-12-30 16:18 UTC, nakiwuge commented on src/components/global/MenuComponent.js
> +      console.log('props.notifsData ===> ', props.notifsData);
remove console

2019-12-30 16:18 UTC, nakiwuge commented on src/components/global/MenuComponent.js
> +      console.log('unreadNotifs ===> ', unreadNotifs);
remove the console

2019-12-30 16:20 UTC, nakiwuge commented on src/components/pages/notifications/NotificationItem.js
> +  state = {
Remove empty state and if you are not changing state make this a functional component

2019-12-30 16:21 UTC, nakiwuge commented on src/components/pages/notifications/NotificationItem.js
> +    console.log('notifId ===> ', notifId);
Remove this console

2019-12-30 16:23 UTC, nakiwuge commented on src/components/pages/notifications/Notifications.js
> +    const { getNotifsAction } = props;
Add a new line here

2019-12-30 16:23 UTC, nakiwuge commented on src/components/pages/notifications/Notifications.js
> +    const { notifsData } = props;
Add a new line here

2019-12-30 16:24 UTC, nakiwuge commented on src/components/pages/profiles/UserProfile.js
> +    const { data } = this.props;
move the constants to the top

2019-12-30 16:24 UTC, nakiwuge commented on src/reducers/allNotifsReducer.js
> +  // status: '',
remove commented code

2019-12-30 16:24 UTC, nakiwuge commented on src/reducers/allNotifsReducer.js
> +        // status: 'success',
remove commented code

2019-12-30 16:24 UTC, nakiwuge commented on src/reducers/allNotifsReducer.js
> +        // status: 'error',
remove commented code

2019-12-30 16:25 UTC, nakiwuge commented on src/reducers/allNotifsReducer.js
> +        // status: '',
Remove commented code

2019-12-30 16:25 UTC, nakiwuge commented on src/styles/components/menubar.scss
> +	// justify-content: space-between;
Remove commented code

2019-12-30 16:25 UTC, nakiwuge commented on src/styles/notifications.scss
> +  // border-radius: 100%;
Remove commented code

2019-12-30 16:44 UTC, nakiwuge requested changes
Great work @nignanthomas I am impressed with your work however kindly work on the feedback below.
 - Give the `Mark all as read` a blue color so that it stands out.
- A user should be able to reverse the `Mark all as read` action (Marl all as unread)
- You should not show the `request id` in the notification just leave the word REQUEST
- The `modal/notifications panel` is not aligned with the `Notification tab` on the menu when the user has no notifications.
- The Mark as read on the notification page is not working as expected. as shown in the gif below.
- I have left other comments on the pr.

![Dec-30-2019 19-41-25 no](https://user-images.githubusercontent.com/9887151/71591252-c0267780-2b3c-11ea-8f3b-64a4a1378316.gif)

2019-12-31 13:01 UTC, nakiwuge approved these changes

2019-12-31 13:26 UTC, merged