#168781643  Edit travel requests with "Open" status
andela/caret-bn-frontend pull request #42
Opened 2019-12-27 19:37 UTC by sabin18

#### What does this PR do?
-PR to allow a user to edit request
#### Description of Task to be completed?
- add edit request action
- add edit request functionality
#### How should this be manually tested?
- Clone ft-edit-request-168781643 branch
- run `npm i`
- run `npm run dev`
- Click on edit button to edit your request
#### Any background context you want to provide?
`N/A`
#### What are the relevant pivotal tracker stories?
[#168781643](https://www.pivotaltracker.com/story/show/168781643)
#### Screenshots (if appropriate)
<img width="1345" alt="Screen Shot 2019-12-27 at 21 37 08" src="https://user-images.githubusercontent.com/47029978/71530166-1acb9380-28f1-11ea-94b7-22e38d2dd1ab.png">

#### Questions:
`N/A`

2020-01-05 11:32 UTC, ngireric123 approved these changes
LGTM

2020-01-05 11:35 UTC, ngireric123 commented
Great job 
However, @sabin18 kindly raise your coverage to >= 90%

2020-01-05 18:45 UTC, alainmateso requested changes
Great job @sabin18 however, I've noticed the following anomalies:
- When editing a multi-city trip, if whatever I edit on one destination is reflected in the rest of the destinations. For example, if I want to edit the reasons for any destination, other destinations change to that as well. In this case, if I edit for example the arrival date, the next trip's information changes to that new date which makes editing that request impossible. 

- In the middle of editing a request, when I press the cancel button, it only disables the fields but the information remains the one I was inputting. This gives the user the wrong impression that their changes were accepted which is not true. I believe canceling should put back the initial information that was present when the request was loaded.

Kindly look into that and kudos for a great job

2020-01-06 15:14 UTC, nakiwuge commented on src/views/requests/SingleRequest.js
> +    this.handleEdit = this.handleEdit.bind(this);
Do not bind use arrow functions and the state directly

2020-01-06 15:15 UTC, nakiwuge commented on src/views/requests/SingleRequest.js
> +      isDisabled: true,
destructure `this.props.singleData`

2020-01-06 15:15 UTC, nakiwuge commented on src/views/requests/SingleRequest.js
> +
Remove this line

2020-01-06 15:17 UTC, nakiwuge commented on src/views/requests/SingleRequest.js
> +    const { name } = target;
Add a new line

2020-01-06 15:33 UTC, nakiwuge requested changes
Good job @sabin18. Kindly work on the feedback below.
- The user should only view the `Edit request` button when the request is pending
- The manager should not view the `Edit Request` button unless the request belongs to him/her.
- When a user clicks cancel after changing some values the values changed remain. Ensure that when the cancel button is clicked the original data is displayed.
- When the save button is loading disable the cancel button
- Editing the destination field is not working
- Write tests for your feature

2020-01-08 12:51 UTC, alainmateso approved these changes

2020-01-08 14:41 UTC, nakiwuge approved these changes

2020-01-08 14:41 UTC, merged