#168781652: like and unlike accommodation
andela/caret-bn-frontend pull request #43
Opened 2019-12-29 22:43 UTC by alainmateso

#### What does this PR do?
Like and unlike accommodations

#### Description of Task to be completed?
- users can like accommodations
- users can unlike accommodations
- users can see the total number of likes and dislikes of an accommodation

#### How should this be manually tested?

- Clone this branch 
- run `npm i`
- run `npm run dev`
- navigate to` http://localhost:<:port>/accommodations/:slug`
- press like or dislike button

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?

#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2019-12-30 at 00 33 26" src="https://user-images.githubusercontent.com/50104386/71563670-2d360080-2a9c-11ea-9712-3686fc793ddb.png">
<img width="1440" alt="Screen Shot 2019-12-30 at 00 33 55" src="https://user-images.githubusercontent.com/50104386/71563702-9ddd1d00-2a9c-11ea-8fff-a94c037844e8.png">

#### Questions:
N/A

2019-12-30 09:48 UTC, ngireric123 reviewed
@alainmateso  good job. Kindly increase your test coverage to 90%

2019-12-30 10:08 UTC, sabin18 requested changes
Good job @alainmateso. However, make likes more visible on view  all accommodations.

2019-12-30 10:27 UTC, ngireric123 approved these changes
LGTM

2019-12-30 10:42 UTC, sabin18 approved these changes

2019-12-30 16:57 UTC, nakiwuge commented on src/components/pages/SingleAccommodation.js
> +    this.handleLike = this.handleLike.bind(this);
Do not bind be consistent

2019-12-30 16:59 UTC, nakiwuge commented on src/styles/pages/allAccommodation.scss
> +}
Add a line at the end of the file

2019-12-30 17:00 UTC, nakiwuge commented on src/tests/componentTests/likeUnlikeTest.spec.js
> +        console.log('wrapper', wrapper.html())
Remove console.log

2019-12-30 17:01 UTC, nakiwuge commented on src/tests/actionsTests/likeUnlikeActionTest.spec.js
> +});
Add a line at the end of the file

2019-12-30 17:01 UTC, nakiwuge commented on src/tests/componentTests/likeUnlikeTest.spec.js
> +});
Add a line at the end of the file

2019-12-30 17:01 UTC, nakiwuge commented on src/tests/componentTests/likeUnlikeTest.spec.js
> +
Remove this line

2019-12-30 17:04 UTC, nakiwuge requested changes
@alainmateso this is good work however kindly add thumbs up and thumbs down icons on each accommodation on the `get all accommodations` page and give each a different color.

I have left other comments on the pr.

2019-12-31 13:05 UTC, nakiwuge approved these changes

2019-12-31 15:09 UTC, merged