#170421866 -  view high rated accommodations
andela/caret-bn-frontend pull request #44
Opened 2019-12-30 08:44 UTC by sabin18

#### What does this PR do?
PR  to view high rated accommodations
#### Description of Task to be completed?
- add view high rated components
- add view high rated action
#### How should this be manually tested?
- Clone ft-notifications-pane-168781628 branch
- run `npm i`
- run `npm run dev`
- after login, you will navigate to the home page where you will see high rate accommodations
#### Any background context you want to provide?
`N/A`
#### What are the relevant pivotal tracker stories?
[#170421866](https://www.pivotaltracker.com/story/show/170421866)
#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2019-12-30 at 10 42 38" src="https://user-images.githubusercontent.com/47029978/71574384-2be2f300-2af1-11ea-89ff-5b9f1d4c782f.png">

#### Questions:
`N/A`

2019-12-30 10:27 UTC, alainmateso approved these changes
LGTM

2019-12-30 18:33 UTC, Cheza-Dzabala approved these changes
Awesome job

2019-12-30 19:51 UTC, nakiwuge commented on src/components/pages/landingPage/HighRatedAccommodations.js
> +
Remove this line

2019-12-30 19:51 UTC, nakiwuge commented on src/components/pages/landingPage/HighRatedAccommodations.js
> +      const { highRated } = this.props;
Add a new line

2019-12-30 19:52 UTC, nakiwuge commented on src/components/pages/landingPage/HighRatedAccommodations.js
> +      const { getHighRatedAccommodation } = this.props;
Add a new line

2019-12-30 20:07 UTC, nakiwuge requested changes
Good job @sabin18. Kindly work on the feedback below.
- Make the `r ` in the heading `High rated` Capital.
- As shown in the screen shot below the high rated images are not alligned with `All destinations`. Ensure that the image sizes are aligned when the screen size reduces.
- The rating also moves from the blue background when in mobile view.
- I have left other comments on the pr




![Screenshot_20191230-225744](https://user-images.githubusercontent.com/9887151/71598510-25d42d00-2b58-11ea-9535-60f90debfa08.png)

2020-01-01 14:39 UTC, nakiwuge approved these changes

2020-01-01 14:40 UTC, merged