#168781634 user request comment
andela/caret-bn-frontend pull request #46
Opened 2019-12-31 08:59 UTC by ngireric123

- Added gitignore file
- Rebase from develop

[Finishes #168781634]

#### What does this PR do?
- Add a comment on a request
#### Description of Task to be completed?
- Admin can comment on a request
- A requester can comment on his/her request

#### How should this be manually tested?

- Clone this branch
- run npm i
- run npm run dev
- in your browser navigate to localhost:<:port>/requests
- click on one request

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#168781634
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/38130305/71615915-551c8580-2bbc-11ea-913a-320aa678f1ea.png)

#### Questions:
N/A

2019-12-31 15:53 UTC, nignanthomas commented on src/styles/pages/comments.scss
> +}
Add eof line here

2019-12-31 15:53 UTC, nignanthomas commented on src/styles/requests/requests.scss
>  }
Add eof line here

2019-12-31 15:54 UTC, nignanthomas commented on src/tests/actionsTests/commentActionTest.spec.js
> +        // console.log('calledActions', calledActions);
Remove console.logs

2019-12-31 15:54 UTC, nignanthomas commented on src/tests/commentDisplayTest.spec.js
> +      // data-test="comment"
Remove commented code

2019-12-31 15:55 UTC, nignanthomas commented on src/components/pages/requests/CommentDisplay.js
> +  // handle submit
Remove comment

2019-12-31 15:55 UTC, nignanthomas commented on src/tests/commentDisplayTest.spec.js
> +      console.log(component.debug());
Remove console.logs

2019-12-31 15:56 UTC, nignanthomas commented on src/tests/commentDisplayTest.spec.js
> +  describe('Signup Test Suite', () => {
Rename the describe to match your test suite.

2019-12-31 15:57 UTC, nignanthomas commented on src/actions/commentAction.js
> +export const setComment = (userData, requestId) => (dispatch) => backendCall.post(`/comments/${requestId}`, userData, { headers })
I trust you could rename `userData` ==> `comment` since it is a comment object.

2019-12-31 16:00 UTC, nignanthomas commented on src/components/pages/requests/CommentDisplay.js
> +import draftToHtml from 'draftjs-to-html';
What are you using these for?
If they are not used in your component, I think you can remove them.

2019-12-31 16:01 UTC, nignanthomas commented on src/styles/pages/comments.scss
> +    margin-bottom: 25px;
Revise the indentation

2019-12-31 16:07 UTC, nignanthomas requested changes
Great job here bro
However @ngireric123, kindly implement the feedback I left
And raise your coverage to >= 90%

And display, the time of the post like `x hours ago` below the comment and you can make it small

2020-01-02 16:09 UTC, sabin18 approved these changes
good job @ngireric123 , Please increase test coverage.

2020-01-02 17:09 UTC, nakiwuge commented on src/components/pages/requests/CommentDisplay.js
> +    e.preventDefault();
add a new line

2020-01-02 17:10 UTC, nakiwuge commented on src/components/pages/requests/CommentDisplay.js
> +    };
Add a new line

2020-01-02 17:10 UTC, nakiwuge commented on src/components/pages/requests/CommentDisplay.js
> +    const { data, commentData } = this.props;
Add a new line

2020-01-02 17:56 UTC, nakiwuge requested changes
@ngireric123 good job on the implementation. I have left comments on your pr also work on the feedback below.
- Make the comments field a text field and modify the commends display to look like something like this 
<img width="1270" alt="Screenshot 2020-01-02 at 20 05 55" src="https://user-images.githubusercontent.com/9887151/71682965-44c5ff80-2da2-11ea-9eee-29fb20b1debe.png">

- Add a loader to the post comment button
- The latest comment should be on top of all comments
- When a user is typing a comment this is what happens kindly fix that.
![Jan-02-2020 19-08-38 comments](https://user-images.githubusercontent.com/9887151/71682999-58716600-2da2-11ea-8fa0-306820ee8315.gif)

2020-01-06 16:31 UTC, nignanthomas approved these changes

2020-01-07 11:40 UTC, nakiwuge approved these changes

2020-01-07 11:40 UTC, merged