#168781633 - Manager Approve Reject Requests
andela/caret-bn-frontend pull request #48
Opened 2019-12-31 15:31 UTC by nignanthomas

#### What does this PR do?
Manager Approve Reject Requests.

#### Description of Task to be completed?
- Create processReqquestAction.
- Create ProcessRequest reusable button component.
- Create tests.

#### How should this be manually tested?
- Clone ft-approve-reject-requests-168781633 branch
- run `npm i`
- run `npm run dev`
- Login as a Manager and click on `Manage Requests` in the Menu

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168781633](https://www.pivotaltracker.com/story/show/168781633)

#### Screenshots (if appropriate)
<img width="1084" alt="Screen Shot 2019-12-31 at 17 25 58" src="https://user-images.githubusercontent.com/42959540/71625956-469d9080-2bf3-11ea-8bd0-a6c6ed46fb5f.png">
<img width="1083" alt="Screen Shot 2019-12-31 at 17 26 14" src="https://user-images.githubusercontent.com/42959540/71625957-47362700-2bf3-11ea-98c6-6a1fb8c44b48.png">

#### Questions:
N/A

2019-12-31 17:07 UTC, ngireric123 requested changes

2019-12-31 17:07 UTC, ngireric123 commented on src/components/pages/requests/ProcessRequest.js
> +
remove one line

2019-12-31 17:07 UTC, ngireric123 commented on src/styles/requests/requests.scss
>  }
add new line

2019-12-31 17:07 UTC, ngireric123 commented on src/tests/reducersTests/processRequestReducerTest.spec.js
> +});
add new line

2019-12-31 17:13 UTC, ngireric123 approved these changes
LGTM

2020-01-01 10:44 UTC, sabin18 requested changes
Good job @nignanthomas , put approve and reject button below the view request button to make it look good.

2020-01-01 14:48 UTC, nakiwuge commented on src/components/pages/requests/ProcessRequest.js
> +    const { action, id } = props;
Add a new line

2020-01-01 14:49 UTC, nakiwuge commented on src/components/pages/requests/ProcessRequest.js
> +    const { action, variant } = this.props;
Add a new line

2020-01-01 14:58 UTC, nakiwuge requested changes
Good job @nignanthomas. Kindly work on the feedback below.
- The user should receive a confirmation message when the click `Approve/Reject`. Something like `Are you sure you want to approve/reject this request?`. This should be a reusable component because it will also be used on DELETE.
- Disable the `Approve` button when the loader is on the `Reject` button and vice versa
- Go through other comments I have left on the pr

2020-01-02 18:26 UTC, nakiwuge approved these changes

2020-01-02 18:27 UTC, merged