#168781638 user edit delete comment
andela/caret-bn-frontend pull request #49
Opened 2020-01-02 15:35 UTC by ngireric123

#### What does this PR do?
- Edit or delete a comment
#### Description of Task to be completed?
- user can delete or edit his/her comment

#### How should this be manually tested?

- Clone this branch
- run npm i
- run npm run dev
- in your browser navigate to localhost:<:port>/requests
- click on comments
- edit or delete comment

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#168781638
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/38130305/71675364-4a155100-2d86-11ea-8cb5-30cb4d2cd11d.png)
![image](https://user-images.githubusercontent.com/38130305/71675378-526d8c00-2d86-11ea-8340-5826400179e0.png)

#### Questions:
N/A

2020-01-07 12:40 UTC, alainmateso approved these changes
LGTM

2020-01-07 15:21 UTC, Cheza-Dzabala commented
Hi @ngireric123 Great job! However please make the following changes:

1. An edited comment should not jump to the top of the pile, it should remain in its original position but may have a small tag that says `edited`

2. Based on the image below, this design is not very intuitive. add an extra Check Mark icon so the user clicks when they finish commenting. 

![Screen Shot 2020-01-07 at 17 15 32](https://user-images.githubusercontent.com/13886438/71905893-b66ec680-3171-11ea-9975-2de65656ed41.png)

That aside, great job

2020-01-07 15:45 UTC, nakiwuge commented on src/components/pages/requests/CommentDisplay.js
> +    const comment = { comment: draftComment };
Add a new line

2020-01-07 15:46 UTC, nakiwuge commented on src/components/pages/requests/CommentDisplay.js
> +    const { comment, id } = e.target;
Add a new line

2020-01-07 15:47 UTC, nakiwuge commented on src/tests/actionsTests/commentActionTest.spec.js
> +
Remove these lines

2020-01-07 15:47 UTC, nakiwuge commented on src/tests/actionsTests/commentActionTest.spec.js
> +
Remove the above lines

2020-01-07 15:48 UTC, nakiwuge commented on src/views/requests/SingleRequest.js
> +export default connect(mapStateToProps, { singleRequestAction, processRequestAction })(SingleRequest);
Add a line at the end of the file

2020-01-07 15:51 UTC, nakiwuge requested changes
@ngireric123 good job however kindly add a loader on  DELETE

2020-01-07 16:45 UTC, Cheza-Dzabala approved these changes

2020-01-08 08:00 UTC, nakiwuge commented on src/components/pages/requests/CommentDisplay.js
> +
Remove this line

2020-01-08 08:43 UTC, nakiwuge approved these changes

2020-01-08 08:44 UTC, merged