#170514634 - Users view bookings
andela/caret-bn-frontend pull request #50
Opened 2020-01-04 17:13 UTC by nignanthomas

#### What does this PR do?
Users view bookings

#### Description of Task to be completed?
- Create actions/reducers.
- Create MyBookings Component.
- Create tests.

#### How should this be manually tested?
- Clone ft-view-bookings-170514634 branch
- run `npm i`
- run `npm run dev`
- Login as a User and click on `My Bookings` in the Menu

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#170514634](https://www.pivotaltracker.com/story/show/170514634)

#### Screenshots (if appropriate)
<img width="1436" alt="Screen Shot 2020-01-04 at 19 07 27" src="https://user-images.githubusercontent.com/42959540/71769173-3e609080-2f26-11ea-9e3b-a4afd11817ed.png">

#### Questions:
N/A

2020-01-05 11:11 UTC, Cheza-Dzabala requested changes
@nignanthomas Really nicely done. One request though, can the bookings be organized into 3. 

1. Pending
2. Approved
3. Rejected

It'll make it easier for the user to navigate.

Question: Are these bookings sorted in any way? 

Secondly, the view single booking page has so much space on it. 
1. Is it necessary seeing as how it does not show any new information? (Opinion Request, not change request)
2. Can it be better placed (Maybe centrally)? (Opinion Request, not change request)

2020-01-05 19:10 UTC, alainmateso requested changes
Great job @nignanthomas however, I believe the following changes should be implemented:
- when viewing a specific booking, kindly center the card that has the booking information.
- I believe when viewing a specific booking, it would be better to see the rest of the available information about that booked accommodation (like its image and cost at least). I feel like, it doesn't make any difference viewing a specific booking since all information is already displayed when viewing all bookings.

Kudos for the awesome job

2020-01-06 13:58 UTC, nakiwuge commented on src/components/pages/OneBooking.js
> +    const { id } = props.match.params;
Add a new line

2020-01-06 13:59 UTC, nakiwuge commented on src/styles/components/menubar.scss
> +// .top-navbar {
remove commented code

2020-01-06 14:00 UTC, nakiwuge commented on src/tests/MyBookingsTest.spec.js
> +    // console.log('component.dive() ===> ', component.find('Component').dive());
remove commented code

2020-01-06 14:00 UTC, nakiwuge commented on src/tests/actionsTests/getOneBookingTest.spec.js
> +});
Add a new line at the end of the file

2020-01-06 14:15 UTC, nakiwuge requested changes
@nignanthomas good job on the implementation. kindly work on the feedback below.
- Using tabs for filtering statuses was a good idea but they are not blending in well with the design so kindly user a dropdown to filter through bookings.
- Make the card heading bold and give it the color of the navbar
- There is a mix up in the Menu. The host can now view `My requests` page and they cannot view the `Accommodations` page.
- Link the booking in notifications to the view single booking page.
- Align the card with the All button. The screenshot below shows the cards are not aligned
<img width="1440" alt="Screenshot 2020-01-06 at 17 07 58" src="https://user-images.githubusercontent.com/9887151/71823306-f6697700-30a7-11ea-97ce-ad599700f735.png">

2020-01-06 17:16 UTC, Cheza-Dzabala approved these changes
LGTM

2020-01-07 12:22 UTC, alainmateso approved these changes

2020-01-07 16:23 UTC, nakiwuge approved these changes

2020-01-07 16:24 UTC, merged