FT: Users Bookmark Accommodations
andela/caret-bn-frontend pull request #53
Opened 2020-01-07 11:09 UTC by Cheza-Dzabala

#### What does this PR do?

- Adds a bookmark.js file responsible for 

#### Description of Task to be completed?
- Allow a user to bookmark an accommodation
- Allow a user to remove a bookmarked accommodation
- Allow a user to view their bookmarks

#### How should this be manually tested?
- Clone this repository
- Run ` npm run install `
- Run` npm run dev`
- Log in as a user
- Navigate to the` accommodaitons list ` page
- Hit the `Star` icon
- VIew `My Bookmarks` page
#### Any background context you want to provide?
N/ A
#### What are the relevant pivotal tracker stories?

##### #170514832, #170514825]

#### Screenshots (if appropriate)

<img width="1672" alt="Screen Shot 2020-01-07 at 13 04 26" src="https://user-images.githubusercontent.com/13886438/71891106-8235de80-314e-11ea-8b51-584c9bcf1905.png">
<img width="1028" alt="Screen Shot 2020-01-07 at 13 04 51" src="https://user-images.githubusercontent.com/13886438/71891108-8235de80-314e-11ea-8992-9ad744834d67.png">
<img width="467" alt="Screen Shot 2020-01-07 at 13 05 05" src="https://user-images.githubusercontent.com/13886438/71891109-8235de80-314e-11ea-9a30-c26ca46925f6.png">
<img width="645" alt="Screen Shot 2020-01-07 at 13 05 24" src="https://user-images.githubusercontent.com/13886438/71891110-82ce7500-314e-11ea-9493-184a42a065f6.png">

#### Questions:
N / A

2020-01-07 12:20 UTC, alainmateso requested changes
Good job @Cheza-Dzabala! However, I believe when viewing the bookmarks image section should be of the same size on each card to make it look better. Also putting the view accommodation button at the bottom of the card would look nicer since now they don't seem to align well depending on different content.

2020-01-07 12:23 UTC, nakiwuge commented on src/actions/bookmarkActions.js
> +
Remove this space

2020-01-07 12:24 UTC, nakiwuge commented on src/components/pages/accommodations/BookmarkStar.js
> +
Remove this space

2020-01-07 12:24 UTC, nakiwuge commented on src/components/pages/accommodations/BookmarkStar.js
> +class BookmarkStar extends Component {
Rename this class to `BookMark`

2020-01-07 12:24 UTC, nakiwuge commented on src/components/pages/accommodations/BookmarkStar.js
> +    const { bookmarkAccommodation, slug } = this.props;
Add a new line

2020-01-07 12:25 UTC, nakiwuge commented on src/components/pages/accommodations/BookmarkStar.js
> +      processedBookmarking: !this.state.processedBookmarking,
destructure the state

2020-01-07 12:28 UTC, nakiwuge commented on src/views/Bookmarks.js
> +                  <Card.Img variant="top" src={(typeof (bookmark.accommodation.images) === 'string') ? bookmark.accommodation.images : bookmark.accommodation.images[0]} />
destructure accommodation from bookmark

2020-01-07 12:35 UTC, alainmateso approved these changes

2020-01-07 12:37 UTC, nakiwuge requested changes
@Cheza-Dzabala good job. Kindly work on the feedback below.
- A user should be able to remove a bookmark from the list of bookmarks on the `my bookmarks` page.
- Give the bookmarks page a heading
- Give the images of the accommodations on `my bookmarks` page the same size
- Capitalize the accommodations tittles
- Reduce the space between the location icon and location
- Add some space below available rooms
- Reduce the space below the `View Accommodations button`
<img width="1440" alt="Screenshot 2020-01-07 at 15 19 50" src="https://user-images.githubusercontent.com/9887151/71895895-553ff680-3163-11ea-9925-8c3b89a24687.png">

2020-01-07 15:29 UTC, nignanthomas requested changes
Great job so far @Cheza-Dzabala 
However, I suggest you return the right currency on the accommodation which is apprently not the case as you can see in the screenshot below. I had noticed the same in all accommodations or single accommodation. It would be great if you could correct that as well.
👍 

<img width="1403" alt="Screen Shot 2020-01-07 at 17 25 38" src="https://user-images.githubusercontent.com/42959540/71906685-30ec1600-3173-11ea-950d-81ad6bf29b2b.png">

2020-01-08 07:39 UTC, nignanthomas approved these changes

2020-01-08 07:52 UTC, nakiwuge approved these changes

2020-01-08 07:53 UTC, merged