#170542128 view deactivated accommodation
andela/caret-bn-frontend pull request #54
Opened 2020-01-08 05:17 UTC by ngireric123

… accommodation

- travel admin can view deactivated accommodation

[Finishes #170542128]

#### What does this PR do?
- Get deactivated accommodation
#### Description of Task to be completed?
- All admin to get all accommodation
#### How should this be manually tested?
- Clone this branch
- run npm i
- run npm run dev .      
- in your browser navigate to localhost:<:port>/deactivated-accommodations

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
- #170542128
#### Screenshots (if appropriate)

#### Questions:
N/A

2020-01-08 15:21 UTC, sabin18 approved these changes
good job @ngireric123 .

2020-01-08 16:55 UTC, alainmateso requested changes
Good job @ngireric123, however, ensure that a supplier cannot  view deactivated accommodations as well as see the that 'deactivated accommodations' button because if a supplier clicks it, the app breaks. Also, make sure the buttons align well with the accommodations cards on smaller devices.

2020-01-08 17:49 UTC, alainmateso approved these changes

2020-01-09 09:02 UTC, nakiwuge commented on src/components/pages/DeactivatedAccommodation.js
> +    const userInfo = isAuthenticated();
Put the const above

2020-01-09 09:08 UTC, nakiwuge commented on src/components/pages/DeactivatedAccommodation.js
> +  showSearch = () => {
Why are you searching? Was this part of your task?

2020-01-09 09:08 UTC, nakiwuge commented on src/components/pages/DeactivatedAccommodation.js
> +  handleLike = async (slug, action) => {
Why are you liking? Was this part of your task?

2020-01-09 09:15 UTC, nakiwuge commented on src/components/pages/DeactivatedAccommodation.js
> +  handleDislike = async (slug, action) => {
Same here please give your method a better name. something like `getDislikes`

2020-01-09 09:15 UTC, nakiwuge commented on src/components/pages/DeactivatedAccommodation.js
> +    console.log('acc', accommodationDeactivatedData);
Remove console.log

2020-01-09 09:15 UTC, nakiwuge commented on src/components/pages/DeactivatedAccommodation.js
> +    let displayItems = {};
Add a new line

2020-01-09 09:16 UTC, nakiwuge commented on src/components/pages/DeactivatedAccommodation.js
> +    const { isLoading, showSearch } = this.state;
Add anew line

2020-01-09 09:17 UTC, nakiwuge commented on src/components/pages/accommodations/DeactivatedListItem.js
> +
Remove this line

2020-01-09 10:06 UTC, nakiwuge requested changes
@ngireric123 good job. kindly work on the feedback below.
- Ensure that a user cannot search for an accommodation that is not deactivated on when on the `deactivated accommodations` page.
- Ensure that a user cannot search for an accommodation that is deactivated on when on the `all accommodations` page.
- Give the deactivated accommodations page a heading

2020-01-10 11:18 UTC, nakiwuge approved these changes

2020-01-10 11:18 UTC, merged