#168781655 - Get trips stats
andela/caret-bn-frontend pull request #57
Opened 2020-01-08 20:28 UTC by nignanthomas

#### What does this PR do?
Users view bookings

#### Description of Task to be completed?
- Create actions/reducers for getStats.
- Create component and route for stats.
- Create tests.

#### How should this be manually tested?
- Clone ft-trips-stats-168781655 branch
- run `npm i`
- run `npm run dev`
- Click on `Stats` in the `SearchBar`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168781655](https://www.pivotaltracker.com/story/show/168781655)

#### Screenshots (if appropriate)
<img width="1201" alt="Screen Shot 2020-01-08 at 22 23 42" src="https://user-images.githubusercontent.com/42959540/72013158-06c75080-3266-11ea-8dc1-135e92694e69.png">

#### Questions:
N/A

2020-01-08 20:37 UTC, ngireric123 approved these changes
LGTM

2020-01-09 09:53 UTC, Cheza-Dzabala requested changes
Great job @nignanthomas however, I have a few changes I'd like to suggest.

1. Please remove the `stats button` from the `search bar` and place it above it. 
2. The `date range` inputs must be placed on a white background.
3. Please line up the `date range` with the results from a search

2020-01-09 09:53 UTC, Cheza-Dzabala commented on src/tests/actionsTests/requestsActionsTest.spec.js
> +
remove this line

2020-01-09 11:12 UTC, nakiwuge commented on src/views/requests/RequestsStats.js
> +  // componentDidMount = async () => {
remove commented code

2020-01-09 11:12 UTC, nakiwuge commented on src/views/requests/RequestsStats.js
> +      console.log('statsParams ===> ', statsParams);
Remove console

2020-01-09 11:13 UTC, nakiwuge commented on src/views/requests/RequestsStats.js
> +                {/* <i className="fa fa-times reset-cross" aria-hidden="true" onClick={this.resetDate} /> */}
Remove commented code

2020-01-09 11:26 UTC, nakiwuge requested changes
Good job @nignanthomas however kindly remove the stats button from the search form and either add it on the menu component or put it on the right aligned it with the Search By button.

2020-01-09 16:28 UTC, Cheza-Dzabala approved these changes
LGTM @nignanthomas

2020-01-09 16:42 UTC, Cheza-Dzabala approved these changes

2020-01-10 10:49 UTC, nakiwuge approved these changes

2020-01-10 10:50 UTC, merged