#168781620- Configure storybook for component development
andela/caret-bn-frontend pull request #6
Opened 2019-11-26 14:38 UTC by sabin18

#### What does this PR do?
PR to add storybook 
#### Description of Task to be completed?
- install storybook
- add storybook configuration
#### How should this be manually tested?
- clone https://github.com/andela/caret-bn-frontend.git
- checkout to ch-configure-storybook-168781620
- Run npm install
- Run npm run storybook
#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
[#168781620](https://www.pivotaltracker.com/story/show/168781620)
#### Screenshots (if appropriate)
<img width="1432" alt="Screen Shot 2019-11-26 at 16 33 53" src="https://user-images.githubusercontent.com/47029978/69642545-93c59a00-106a-11ea-9e9c-c92f304c8f83.png">

#### Questions:

2019-11-27 09:21 UTC, alainmateso approved these changes

2019-11-27 09:46 UTC, Cheza-Dzabala approved these changes
thumbs up

2019-11-27 10:26 UTC, nakiwuge requested changes
@sabin18 good job, however kindly use the components that are already in the codebase for the story book.

2019-11-28 11:17 UTC, nakiwuge approved these changes

2019-11-28 11:17 UTC, merged