#170542375-implement profile feedback
andela/caret-bn-frontend pull request #61
Opened 2020-01-10 06:03 UTC by ngireric123

#### What does this PR do?
implement profile feedback
#### Description of Task to be completed?
- Change Department text input to a dropdown
- Fix the bug on submission of space as the value of the username field
- Disable the Company field since users are from the same company
- A host should not view My requests page
#### How should this be manually tested?
- Clone ch-feedback-notifications-170578497 branch
- run npm i
- run npm run dev
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#170542375
#### Screenshots (if appropriate)

#### Questions:
N/A

2020-01-10 11:57 UTC, sabin18 approved these changes

2020-01-10 12:09 UTC, nakiwuge commented on src/components/pages/profiles/UserProfile.js
> +    // this.setState({ isLoading: true });
remove commented code

2020-01-13 10:19 UTC, nignanthomas requested changes
Great job implementing the feedback @ngireric123.
However I have noticed, the message on phone error could be more human-readable.
<img width="975" alt="Screen Shot 2020-01-13 at 12 13 07" src="https://user-images.githubusercontent.com/42959540/72248004-ca497b00-35fe-11ea-9dcc-d309cb84991f.png">

And when I update my profile, the MenuComponent fails to display the `username`.
<img width="395" alt="Screen Shot 2020-01-13 at 12 15 11" src="https://user-images.githubusercontent.com/42959540/72248041-e2b99580-35fe-11ea-98e1-ae1a0ca2eea9.png">

2020-01-15 05:32 UTC, nignanthomas approved these changes

2020-01-15 09:46 UTC, sabin18 approved these changes

2020-01-15 13:21 UTC, ceelogre reviewed
Create a review app.

2020-01-16 12:59 UTC, merged