#170514783-activate/deactivate accommodation
andela/caret-bn-frontend pull request #63
Opened 2020-01-12 15:22 UTC by ngireric123

#### What does this PR do?
- activate/deactivate accommodation
#### Description of Task to be completed?
- All  travel admins should activate or deactivate accommodation
#### How should this be manually tested?
- Clone this branch
- run npm i
- run npm run dev   
- in your browser navigate to localhost:<:port>/deactivated
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#170514783
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/38130305/72221073-cadf0480-355f-11ea-9b6b-e7ff4bf613a6.png)

#### Questions:
N/A

2020-01-13 13:37 UTC, Cheza-Dzabala requested changes
Greetings @ngireric123 Seen the app. Good job, however, the feature is not working as it should. All accommodations say "Deactivate Accommodation" even when the accommodation is already deactivated and is awaiting activation. Secondly, no success alerts are displayed upon activation/deactivation. 

I suggest redirection to a single accommodation page when the accommodation is activated.

2020-01-13 13:45 UTC, sabin18 commented on src/components/pages/SingleAccommodation.js
> +
remove these comments.

2020-01-13 13:45 UTC, sabin18 commented on src/tests/accommodationTests/DeactivatedListItemTest.spec.js
> +    // const likeButton = findByTestAttribute(component, 'like-button');
remove these comments.

2020-01-13 13:56 UTC, sabin18 requested changes
good job @ngireric123 , work on the comment I left on this PR and increase test coverage.

2020-01-14 08:21 UTC, sabin18 approved these changes
great job.

2020-01-15 12:44 UTC, Cheza-Dzabala approved these changes

2020-01-15 13:08 UTC, nignanthomas commented on src/actions/accommodationActions.js
> +export const activatedAccommodation = (slug, reasons) => (dispatch) => backendCall.patch(`/accommodations/activate/${slug}`, { reasons }, { headers: activationHeaders })
I suggest you rename the action to `activateAccommodation` since it is an action it should be a verb.

2020-01-15 13:23 UTC, nignanthomas requested changes
Well done @ngireric123 
However I noticed, the following you need to fix:

- When logged in as a requester I should not view `Deactivate Accommodation` button.
Only `Travel Admin` should view it, right?
<img width="1062" alt="Screen Shot 2020-01-15 at 14 54 37" src="https://user-images.githubusercontent.com/42959540/72436934-47652380-37aa-11ea-970a-b519621b0f5d.png">

- Kindly add the `Link` to deactivate in the Single accommodation as well. I don't wanna have to go back to the `All accommodations to deactivate`

- When accessing the `/accommodations/deactivate` as a requester it breaks.
Redirect me to `all accommodations` when I am not a travel admin.
<img width="1424" alt="Screen Shot 2020-01-15 at 15 14 15" src="https://user-images.githubusercontent.com/42959540/72437184-da9e5900-37aa-11ea-8028-b13589eb1e5d.png">

Lemme know as soon as it is fixed. Thanks
**PS**: Fix the failing `codeclimate check`, and I did also leave a comment on the action ☝️

2020-01-16 17:31 UTC, nignanthomas approved these changes

2020-01-16 18:15 UTC, merged