Bg fix reload error 170670470
andela/caret-bn-frontend pull request #64
Opened 2020-01-13 10:45 UTC by Cheza-Dzabala

#### What does this PR do?

Remove redirect links in Menu Component

#### Description of Task to be completed?
Fix reload issue 
Fix social authentication redirection problem

#### How should this be manually tested?
- Clone this Repo
- Run npm install
- Run npm run dev
- Log into the application
- Make change to JSX code
- Watch component reload 

#### Any background context you want to provide?

- Any change to JSX or reloading any page would cause application to reload home page

#### What are the relevant pivotal tracker stories?

##### #170670470

#### Screenshots (if appropriate)
N / A
#### Questions:
N / A

2020-01-13 15:25 UTC, alainmateso approved these changes
LGTM

2020-01-14 09:20 UTC, nignanthomas approved these changes

2020-01-14 10:31 UTC, ceelogre requested changes
Fix CodeClimate health check.

2020-01-15 09:12 UTC, ceelogre approved these changes

2020-01-15 09:45 UTC, merged